# Generated by Django 5.1.1 on 2024-11-18 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_dashboards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmptyWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Widget", max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
                ("refresh_interval", models.PositiveIntegerField(default=60)),
                ("position", models.CharField(blank=True, max_length=40, null=True)),
                ("resizable", models.BooleanField(default=True)),
                ("front_data", models.JSONField(blank=True, null=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="app_dashboards.dashboard",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
