# Generated by Django 5.1.1 on 2024-11-08 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_dashboards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dashboard",
            name="background_color",
        ),
        migrations.RemoveField(
            model_name="dashboard",
            name="background_image",
        ),
        migrations.AlterField(
            model_name="dashboard",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
