# Generated by Django 5.1.1 on 2024-10-28 17:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_dashboards", "0001_initial"),
        ("app_profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SimpleTodoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Widget", max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
                ("refresh_interval", models.PositiveIntegerField(default=60)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="widgets_icons/"
                    ),
                ),
                ("position", models.CharField(blank=True, max_length=40, null=True)),
                ("resizable", models.BooleanField(default=True)),
                ("size", models.CharField(default="medium", max_length=40)),
                ("min_height", models.IntegerField(default=100)),
                ("max_height", models.IntegerField(default=600)),
                ("min_width", models.IntegerField(default=100)),
                ("max_width", models.IntegerField(default=400)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "progress_bar",
                    models.PositiveIntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "border_color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="widget_border_color",
                        to="app_profiles.color",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="widget_background",
                        to="app_profiles.color",
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="app_dashboards.dashboard",
                    ),
                ),
                (
                    "text_color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="widget_text_color",
                        to="app_profiles.color",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        related_name="todo_lists", to="app_widgets.task"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
