# Generated by Django 5.1.1 on 2024-11-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_widgets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simpletodolist",
            name="border_color",
        ),
        migrations.RemoveField(
            model_name="simpletodolist",
            name="color",
        ),
        migrations.RemoveField(
            model_name="simpletodolist",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="simpletodolist",
            name="max_height",
        ),
        migrations.RemoveField(
            model_name="simpletodolist",
            name="max_width",
        ),
        migrations.RemoveField(
            model_name="simpletodolist",
            name="min_height",
        ),
        migrations.RemoveField(
            model_name="simpletodolist",
            name="min_width",
        ),
        migrations.RemoveField(
            model_name="simpletodolist",
            name="size",
        ),
        migrations.RemoveField(
            model_name="simpletodolist",
            name="text_color",
        ),
        migrations.AddField(
            model_name="simpletodolist",
            name="front_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
