# Generated by Django 5.1.1 on 2024-11-20 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_dashboards", "0003_emptywidget_created_at_emptywidget_updated_at"),
        ("app_widgets", "0002_alter_simpletodolist_dashboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="end_hour",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="start_hour",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=True)),
                ("refresh_interval", models.PositiveIntegerField(default=60)),
                ("position", models.CharField(blank=True, max_length=40, null=True)),
                ("resizable", models.BooleanField(default=True)),
                ("front_data", models.JSONField(blank=True, null=True)),
                ("name", models.CharField(default="Timetable", max_length=120)),
                ("title", models.CharField(default="Timetable", max_length=120)),
                ("week_number", models.PositiveIntegerField()),
                ("period", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable",
                        to="app_dashboards.dashboard",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Monday", "monday"),
                            ("Tuesday", "tuesday"),
                            ("Wednesday", "wednesday"),
                            ("Thursday", "thursday"),
                            ("Friday", "friday"),
                            ("Saturday", "saturday"),
                            ("Sunday", "sunday"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        blank=True, related_name="days", to="app_widgets.task"
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="app_widgets.timetable",
                    ),
                ),
            ],
        ),
    ]
