# Generated by Django 5.1.1 on 2024-11-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_widgets", "0003_simpletodolist_polymorphic_ctype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simpletodolist",
            name="polymorphic_ctype",
        ),
        migrations.AddField(
            model_name="simpletodolist",
            name="title",
            field=models.CharField(default="Simple Todo List", max_length=120),
        ),
        migrations.AlterField(
            model_name="simpletodolist",
            name="name",
            field=models.CharField(
                choices=[("Simple Todo List", "simple_todo"), ("Widget", "widget")],
                default="Widget",
                max_length=128,
            ),
        ),
    ]
